config/routes.rb
DescribeMe::Application.routes.draw do
  resources :users, param: :fb_id do
    collection do
      get :sign_in
    end

    member do
      post :describe
    end
  end

  root to: 'users#index', via: :get

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/description.rb
class Description < ActiveRecord::Base
  belongs_to :described, class_name: 'User', foreign_key: 'described_user_id'
  belongs_to :describer, class_name: 'User', foreign_key: 'described_by_user_id'

  def described
    User.find_by_fb_id(self.described_user_id)
  end

  def describer
    User.find_by_fb_id(self.described_by_user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def descriptions
    Description.where("described_user_id = ?", self.fb_id)
  end

  def given_descriptions
    Description.where("described_by_user_id = ?", self.fb_id)
  end

  def facebook_details
    facebook = Koala::Facebook::API.new(self.oauth_token, '16f69b54145dcc55488d4a8963a0c030')
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.extra.raw_info.first_name
      user.last_name = auth.extra.raw_info.last_name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_current_user, except: :sign_in

  # GET /users
  # GET /users.json
  def index
    @friends = current_user.facebook_details.get_connections("me", "friends")
    @data = @friends.map do |item|

      desc = Description.where(described_user_id: item["id"]).map(&:content)
      current_user.facebook_details.get_object(item["id"]).merge({image: current_user.facebook_details.get_picture(item["id"])}).merge({
        descriptions: desc,
        description:  (c = Description.where(described_by_user_id: current_user.uid, described_user_id: item["id"])).empty? ?  "He knows nothing!" : c.first.content
      })
    end

    respond_to do |format|
      format.html {}
      format.json {
        render json: @data.to_json, layout: false, status: 200
      }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user.fb_id), notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user.fb_id), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/:fb_id/describe
  def describe
    p "describing.."
    p params

    if Description.where("described_user_id = ? AND described_by_user_id = ?", params["fb_id"], current_user.facebook_details.get_object("me")["id"]).present?
      @description = Description.where("described_user_id = ? AND described_by_user_id = ?", params["fb_id"], current_user.facebook_details.get_object("me")["id"]).first
      @description.update_attribute(:content, params["description"])
    else
      @description = Description.new({
        described_user_id: params["fb_id"],
        described_by_user_id: current_user.facebook_details.get_object("me")["id"],
        content: params["description"]
      })
      @description.save!
    end


    render :nothing => true
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def sign_in

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_fb_id(params[:fb_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fb_id, :first_name, :middle_name, :last_name, :gender, :link, :username)
    end


    def check_current_user
      redirect_to sign_in_users_path unless current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DescribeMe</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="user_nav">
    <% if current_user %>
      Signed in as <strong><%= current_user.first_name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fb_id %><br>
    <%= f.text_field :fb_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_friend.slim
table
  thead
    tr
      th Image
      th First Name
  tbody
    - @friends.each do |friend|
      tr
        td #{image_tag friend['picture']['data']['url'].to_s}
        td #{friend['name']}

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', user_url(@user.fb_id) %> |
<%= link_to 'Back', users_path %>

app/views/users/index.slim
h1
  | Listing Friends

/table
/  thead
/    tr
/      th Image
/      th First Name
/  tbody
/    - @friends.each do |friend|
/      tr
/        td #{image_tag friend['picture']['data']['url'].to_s}
/        td #{friend['name']}
/
/
hr

div#catalog-example

app/views/users/login.html.erb
<%= image_tag @user['picture']['data']['url'].to_s %>
<%= @user['name'] %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fb:</strong>
  <%= @user.fb_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @user.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Link:</strong>
  <%= @user.link %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user.fb_id) %> |
<%= link_to 'Back', users_path %>